ROLE_SHELL_CONTENT = {
    "student": {
        "hero_eyebrow": "Student Course Portal",
        "section_eyebrow": "Learning Directions",
        "section_title": "请选择已开放的学习内容",
        "section_description": "这里是学生端课程选择页。课程入口按方向整理，大部分内容暂处于锁定状态，已开放内容可优先进入学习门户。",
        "summary_cards": [
            {"label": "已开放方向", "value": "2 个", "hint": "当前可进入 C++ 与 Python 方向"},
            {"label": "体验中方向", "value": "1 个", "hint": "AI 学习入口保持体验态"},
            {"label": "锁定方向", "value": "5 个", "hint": "其余内容将按阶段逐步解锁"},
        ],
        "portal_notice": {
            "title": "学习入口说明",
            "description": "优先进入已开放内容，锁定方向先了解课程结构。未来第一个真实内容会从 C++ > GESP4 > 二维数组专题 接入。",
            "items": [
                "已开放：可以直接进入当前方向的学习门户入口",
                "体验中：可先查看方向内容，等待正式开放",
                "未开放：保持结构展示，后续根据学习阶段解锁",
            ],
        },
        "directions": [
            {
                "slug": "cpp",
                "title": "C++",
                "track": "算法与竞赛",
                "level": "GESP4",
                "phase": "进阶专题",
                "state": "open",
                "status_text": "已开放",
                "description": "以算法思维和编程表达为核心，作为未来真实课程内容接入的第一条学习主线。",
                "tip": "当前优先预留真实内容入口。",
                "hint": "推荐先查看 GESP4 方向专题入口。",
                "action_label": "查看开放入口",
                "action_href": "#cpp-gesp4-entry",
                "focus_entry": {
                    "label": "首个真实内容预留",
                    "status_text": "未来可进入",
                    "path": ["C++", "GESP4", "二维数组专题"],
                    "title": "二维数组专题",
                    "description": "这是未来系统将接入的第一个真实课程内容。本批次只保留入口层级与视觉结构，不接入旧项目代码。",
                },
            },
            {
                "slug": "python",
                "title": "Python",
                "track": "创意编程",
                "level": "基础提升",
                "phase": "项目实践",
                "state": "open",
                "status_text": "已开放",
                "description": "以创意项目和基础语法训练为主，保持学生连续学习体验。",
                "tip": "适合作为当前已开放的常规学习入口。",
                "hint": "可继续进入当前学习方向。",
                "action_label": "进入学习门户",
                "action_href": "#direction-python",
            },
            {
                "slug": "ai",
                "title": "AI",
                "track": "智能探索",
                "level": "启蒙体验",
                "phase": "体验内容",
                "state": "trial",
                "status_text": "体验中",
                "description": "以趣味 AI 认知和基础交互体验为主，当前先展示方向入口。",
                "tip": "体验内容保留中，后续再开放完整学习链路。",
                "hint": "当前可先查看方向说明。",
                "action_label": "查看体验入口",
                "action_href": "#direction-ai",
            },
            {
                "slug": "scratch",
                "title": "Scratch",
                "track": "图形编程",
                "level": "基础启蒙",
                "phase": "待开放",
                "state": "locked",
                "status_text": "未开放",
                "description": "图形化编程方向预留给低龄阶段学生，当前仅展示入口结构。",
                "tip": "后续将根据学习阶段逐步解锁。",
                "hint": "当前暂不可进入。",
            },
            {
                "slug": "pbl",
                "title": "PBL",
                "track": "项目制学习",
                "level": "综合表达",
                "phase": "待开放",
                "state": "locked",
                "status_text": "未开放",
                "description": "跨学科项目学习方向，后续将承接主题任务与成果展示。",
                "tip": "当前保持课程结构占位。",
                "hint": "当前暂不可进入。",
            },
            {
                "slug": "uav",
                "title": "无人机",
                "track": "科技实践",
                "level": "设备实践",
                "phase": "待开放",
                "state": "locked",
                "status_text": "未开放",
                "description": "围绕飞行器和控制逻辑的实践课程入口，当前仅保留门户位置。",
                "tip": "后续将结合设备与课堂安排开放。",
                "hint": "当前暂不可进入。",
            },
            {
                "slug": "thinking",
                "title": "思维",
                "track": "逻辑训练",
                "level": "专项提升",
                "phase": "待开放",
                "state": "locked",
                "status_text": "未开放",
                "description": "面向逻辑推理和问题拆解的训练模块，后续用于强化学习基础。",
                "tip": "当前先保留方向结构。",
                "hint": "当前暂不可进入。",
            },
            {
                "slug": "english",
                "title": "英语",
                "track": "语言支持",
                "level": "课堂辅助",
                "phase": "待开放",
                "state": "locked",
                "status_text": "未开放",
                "description": "用于承接编程英语和课堂表达支持的入口，当前处于锁定展示态。",
                "tip": "后续将按课程搭配开放。",
                "hint": "当前暂不可进入。",
            },
        ],
        "support_label": "Learning Notes",
        "support_title": "学习提醒",
        "support_description": "右侧保留给学生端的学习建议和开放说明，帮助学生快速判断当前可以进入哪些内容。",
        "support_items": [
            {"title": "优先入口", "description": "建议先从已开放方向进入，保持学习节奏稳定。"},
            {"title": "锁定说明", "description": "锁定方向仅展示结构，后续会随学习阶段逐步开放。"},
            {"title": "真实内容预留", "description": "C++ > GESP4 > 二维数组专题 已作为首个真实内容接入口预留。"},
        ],
    },
    "parent": {
        "hero_eyebrow": "Parent Workspace",
        "section_eyebrow": "Profile Shell",
        "section_title": "学生信息卡壳子",
        "section_description": "家长页先以学生信息卡为主，后续可在现有结构上接入学习档案、课堂反馈和沟通记录。",
        "summary_cards": [
            {"label": "本周课程", "value": "2 节", "hint": "与课程安排同步占位"},
            {"label": "课堂反馈", "value": "1 条待查看", "hint": "后续接真实教师反馈"},
            {"label": "学习状态", "value": "专注稳定", "hint": "适合继续保持节奏"},
        ],
        "student_profile": {
            "name": "林一诺",
            "summary": "在读学员 · Python 提升班",
            "campus": "浦东张江校区",
            "grade": "四年级",
            "mentor": "周老师",
            "recent_lesson": "Python 创意编程 · 第 6 课",
        },
        "profile_items": [
            {"label": "当前课程", "value": "Python 创意编程"},
            {"label": "班级分组", "value": "周三晚班"},
            {"label": "入学时间", "value": "2025 年秋季"},
            {"label": "本期目标", "value": "变量、条件与函数启蒙"},
        ],
        "support_label": "Parent Notes",
        "support_title": "家长关注点",
        "support_description": "这一列保留给家长端的重点提醒和沟通入口，当前仅展示结构占位。",
        "support_items": [
            {"title": "课程出勤", "description": "后续会补入每次到课、请假与补课状态。"},
            {"title": "课堂反馈", "description": "后续会在此接教师点评和课后建议。"},
            {"title": "家校沟通", "description": "后续将预留消息、预约沟通和通知入口。"},
        ],
    },
    "teacher": {
        "hero_eyebrow": "Teacher Workspace",
        "section_eyebrow": "Student List",
        "section_title": "学生列表壳子",
        "section_description": "教师页先以学生列表为核心结构，后续可继续接入点名、学习进度、课堂反馈和分班管理。",
        "summary_cards": [
            {"label": "在读学员", "value": "36 人", "hint": "当前班级学生数量占位"},
            {"label": "今日课程", "value": "4 节", "hint": "按教师日程入口预留"},
            {"label": "待跟进", "value": "3 项", "hint": "后续接入作业与反馈任务"},
        ],
        "students": [
            {
                "name": "林一诺",
                "grade": "四年级",
                "course": "Python 创意编程",
                "status": "正常跟进",
                "note": "变量理解稳定，建议增加小题练习。",
            },
            {
                "name": "赵可可",
                "grade": "五年级",
                "course": "趣味算法启蒙",
                "status": "需关注",
                "note": "课堂参与积极，但拆题步骤还需强化。",
            },
            {
                "name": "周子辰",
                "grade": "三年级",
                "course": "图形逻辑实验室",
                "status": "进度良好",
                "note": "图形任务完成度高，可逐步接触更复杂指令。",
            },
            {
                "name": "陈思羽",
                "grade": "六年级",
                "course": "Python 创意编程",
                "status": "待回访",
                "note": "近期缺勤 1 次，后续需要跟进补课安排。",
            },
        ],
        "support_label": "Teaching Notes",
        "support_title": "教学提醒",
        "support_description": "这一列保留给教师端的备课提醒、班级事项和课后跟进提示。",
        "support_items": [
            {"title": "课前确认", "description": "下一步可在此挂接课件、名单与设备检查项。"},
            {"title": "课后记录", "description": "后续将预留课堂表现、作业完成和点评入口。"},
            {"title": "班级协同", "description": "后续可补入教务协同、补课和排课提醒。"},
        ],
    },
    "principal": {
        "hero_eyebrow": "Principal Workspace",
        "section_eyebrow": "Overview Shell",
        "section_title": "概览卡片壳子",
        "section_description": "校长页先以概览卡片和关注面板为核心结构，后续可平滑接入校区运营、教学排布和数据看板。",
        "summary_cards": [
            {"label": "在读学员", "value": "128", "hint": "当前校区总人数占位"},
            {"label": "本周课次", "value": "42 节", "hint": "教学运行总览入口"},
            {"label": "教师在线", "value": "9 位", "hint": "后续接入师资排班状态"},
        ],
        "overview_cards": [
            {"title": "教学运行", "value": "42 节", "description": "本周计划课程，预留课次与开班统计结构。"},
            {"title": "新签试听", "value": "12 组", "description": "预留招生与试听转化入口，不接真实业务逻辑。"},
            {"title": "家校反馈", "value": "96%", "description": "预留满意度与反馈处理面板。"},
            {"title": "排课稳定性", "value": "良好", "description": "预留教师、教室和班级冲突预警位。"},
        ],
        "support_label": "Campus Focus",
        "support_title": "本周关注点",
        "support_description": "这一列保留给校区管理层的关键提醒和待处理事项，当前先展示统一壳子。",
        "support_items": [
            {"title": "教学节奏", "description": "后续可在此汇总课次执行、缺勤和补课提醒。"},
            {"title": "师资排布", "description": "后续将预留教师排课冲突与人力负载入口。"},
            {"title": "运营总览", "description": "后续可补入校区收入、续费和试听转化概览。"},
        ],
    },
}
