ROLE_SHELL_CONTENT = {
    "student": {
        "hero_eyebrow": "Student Workspace",
        "section_eyebrow": "Course Shell",
        "section_title": "课程卡片区",
        "section_description": "课程区按卡片结构预留展示位，下一步可以直接接入真实开课状态、作业提示和学习进度。",
        "summary_cards": [
            {"label": "本周课程", "value": "3 节", "hint": "含 Python、图形与算法启蒙"},
            {"label": "下一节课", "value": "周三 18:30", "hint": "Python 创意编程"},
            {"label": "学习状态", "value": "稳步推进", "hint": "适合保持每周练习节奏"},
        ],
        "courses": [
            {
                "status": "进行中",
                "code": "CM-PY-201",
                "title": "Python 创意编程",
                "description": "从图形绘制、变量和条件判断切入，帮助学生建立编程表达能力。",
                "schedule": "周三 18:30",
                "mentor": "陈老师",
                "progress": "已完成 6 / 12 课次",
            },
            {
                "status": "即将开始",
                "code": "CM-SC-118",
                "title": "趣味算法启蒙",
                "description": "以闯关与拆解思路为核心，预留算法训练模块的接入位置。",
                "schedule": "周六 10:00",
                "mentor": "刘老师",
                "progress": "待开课",
            },
            {
                "status": "专题练习",
                "code": "CM-AR-076",
                "title": "图形逻辑实验室",
                "description": "用于承接图形化编程和课堂实验任务的后续扩展入口。",
                "schedule": "周日 14:00",
                "mentor": "王老师",
                "progress": "课堂任务待接入",
            },
        ],
        "support_label": "Learning Notes",
        "support_title": "学习提醒",
        "support_description": "这一列保留给学生端的短提醒、任务公告和学习建议，当前先以静态占位内容呈现。",
        "support_items": [
            {"title": "上课准备", "description": "建议课前 10 分钟检查账号、网络和输入设备。"},
            {"title": "练习节奏", "description": "当前适合保持每周 2 到 3 次短时练习。"},
            {"title": "作业入口", "description": "后续会在课程卡片中补入课后任务和提交状态。"},
        ],
    },
    "parent": {
        "hero_eyebrow": "Parent Workspace",
        "section_eyebrow": "Profile Shell",
        "section_title": "学生信息卡壳子",
        "section_description": "家长页先以学生信息卡为主，后续可在现有结构上接入学习档案、课堂反馈和沟通记录。",
        "summary_cards": [
            {"label": "本周课程", "value": "2 节", "hint": "与课程安排同步占位"},
            {"label": "课堂反馈", "value": "1 条待查看", "hint": "后续接真实教师反馈"},
            {"label": "学习状态", "value": "专注稳定", "hint": "适合继续保持节奏"},
        ],
        "student_profile": {
            "name": "林一诺",
            "summary": "在读学员 · Python 提升班",
            "campus": "浦东张江校区",
            "grade": "四年级",
            "mentor": "周老师",
            "recent_lesson": "Python 创意编程 · 第 6 课",
        },
        "profile_items": [
            {"label": "当前课程", "value": "Python 创意编程"},
            {"label": "班级分组", "value": "周三晚班"},
            {"label": "入学时间", "value": "2025 年秋季"},
            {"label": "本期目标", "value": "变量、条件与函数启蒙"},
        ],
        "support_label": "Parent Notes",
        "support_title": "家长关注点",
        "support_description": "这一列保留给家长端的重点提醒和沟通入口，当前仅展示结构占位。",
        "support_items": [
            {"title": "课程出勤", "description": "后续会补入每次到课、请假与补课状态。"},
            {"title": "课堂反馈", "description": "后续会在此接教师点评和课后建议。"},
            {"title": "家校沟通", "description": "后续将预留消息、预约沟通和通知入口。"},
        ],
    },
    "teacher": {
        "hero_eyebrow": "Teacher Workspace",
        "section_eyebrow": "Student List",
        "section_title": "学生列表壳子",
        "section_description": "教师页先以学生列表为核心结构，后续可继续接入点名、学习进度、课堂反馈和分班管理。",
        "summary_cards": [
            {"label": "在读学员", "value": "36 人", "hint": "当前班级学生数量占位"},
            {"label": "今日课程", "value": "4 节", "hint": "按教师日程入口预留"},
            {"label": "待跟进", "value": "3 项", "hint": "后续接入作业与反馈任务"},
        ],
        "students": [
            {
                "name": "林一诺",
                "grade": "四年级",
                "course": "Python 创意编程",
                "status": "正常跟进",
                "note": "变量理解稳定，建议增加小题练习。",
            },
            {
                "name": "赵可可",
                "grade": "五年级",
                "course": "趣味算法启蒙",
                "status": "需关注",
                "note": "课堂参与积极，但拆题步骤还需强化。",
            },
            {
                "name": "周子辰",
                "grade": "三年级",
                "course": "图形逻辑实验室",
                "status": "进度良好",
                "note": "图形任务完成度高，可逐步接触更复杂指令。",
            },
            {
                "name": "陈思羽",
                "grade": "六年级",
                "course": "Python 创意编程",
                "status": "待回访",
                "note": "近期缺勤 1 次，后续需要跟进补课安排。",
            },
        ],
        "support_label": "Teaching Notes",
        "support_title": "教学提醒",
        "support_description": "这一列保留给教师端的备课提醒、班级事项和课后跟进提示。",
        "support_items": [
            {"title": "课前确认", "description": "下一步可在此挂接课件、名单与设备检查项。"},
            {"title": "课后记录", "description": "后续将预留课堂表现、作业完成和点评入口。"},
            {"title": "班级协同", "description": "后续可补入教务协同、补课和排课提醒。"},
        ],
    },
    "principal": {
        "hero_eyebrow": "Principal Workspace",
        "section_eyebrow": "Overview Shell",
        "section_title": "概览卡片壳子",
        "section_description": "校长页先以概览卡片和关注面板为核心结构，后续可平滑接入校区运营、教学排布和数据看板。",
        "summary_cards": [
            {"label": "在读学员", "value": "128", "hint": "当前校区总人数占位"},
            {"label": "本周课次", "value": "42 节", "hint": "教学运行总览入口"},
            {"label": "教师在线", "value": "9 位", "hint": "后续接入师资排班状态"},
        ],
        "overview_cards": [
            {"title": "教学运行", "value": "42 节", "description": "本周计划课程，预留课次与开班统计结构。"},
            {"title": "新签试听", "value": "12 组", "description": "预留招生与试听转化入口，不接真实业务逻辑。"},
            {"title": "家校反馈", "value": "96%", "description": "预留满意度与反馈处理面板。"},
            {"title": "排课稳定性", "value": "良好", "description": "预留教师、教室和班级冲突预警位。"},
        ],
        "support_label": "Campus Focus",
        "support_title": "本周关注点",
        "support_description": "这一列保留给校区管理层的关键提醒和待处理事项，当前先展示统一壳子。",
        "support_items": [
            {"title": "教学节奏", "description": "后续可在此汇总课次执行、缺勤和补课提醒。"},
            {"title": "师资排布", "description": "后续将预留教师排课冲突与人力负载入口。"},
            {"title": "运营总览", "description": "后续可补入校区收入、续费和试听转化概览。"},
        ],
    },
}
