STUDENT_PORTAL_CONTENT = {
    "courses": {
        "page_mode": "entry_grid",
        "grid_variant": "courses",
        "hero_eyebrow": "Student Course Portal",
        "page_title": "学生课程选择页",
        "page_description": "请选择已开放的学习入口。",
        "summary_cards": [
            {"label": "已开放", "value": "2 个"},
            {"label": "体验中", "value": "1 个"},
            {"label": "未开放", "value": "5 个"},
        ],
        "entry_hint": "先选大类，再进入下一级。",
        "portal_cards": [
            {
                "slug": "cpp",
                "title": "C++",
                "meta": "算法与竞赛",
                "subtitle": "已开放主入口",
                "note": "GESP / CSP / 机器人编程",
                "state": "open",
                "status_text": "已开放",
                "featured": True,
                "action_label": "进入 C++",
                "action_href": "/student/cpp",
            },
            {
                "slug": "python",
                "title": "Python",
                "meta": "创意编程",
                "subtitle": "基础提升",
                "note": "课程入口已就绪",
                "state": "open",
                "status_text": "已开放",
                "action_label": "查看入口",
                "action_href": "#direction-python",
            },
            {
                "slug": "ai",
                "title": "AI",
                "meta": "智能探索",
                "subtitle": "体验内容",
                "note": "可先体验方向入口",
                "state": "trial",
                "status_text": "体验中",
                "action_label": "查看体验",
                "action_href": "#direction-ai",
            },
            {
                "slug": "scratch",
                "title": "Scratch",
                "meta": "图形编程",
                "subtitle": "基础启蒙",
                "note": "后续分阶段开放",
                "state": "locked",
                "status_text": "未开放",
            },
            {
                "slug": "pbl",
                "title": "PBL",
                "meta": "项目制学习",
                "subtitle": "综合表达",
                "note": "入口位预留",
                "state": "locked",
                "status_text": "未开放",
            },
            {
                "slug": "uav",
                "title": "无人机",
                "meta": "科技实践",
                "subtitle": "设备实践",
                "note": "后续按安排开放",
                "state": "locked",
                "status_text": "未开放",
            },
            {
                "slug": "thinking",
                "title": "思维",
                "meta": "逻辑训练",
                "subtitle": "专项提升",
                "note": "当前保留方向入口",
                "state": "locked",
                "status_text": "未开放",
            },
            {
                "slug": "english",
                "title": "英语",
                "meta": "语言支持",
                "subtitle": "课堂辅助",
                "note": "后续随课程开放",
                "state": "locked",
                "status_text": "未开放",
            },
        ],
    },
    "cpp": {
        "page_mode": "entry_grid",
        "grid_variant": "three",
        "hero_eyebrow": "C++ Learning Portal",
        "page_title": "C++ 学习方向分类页",
        "page_description": "请选择一个 C++ 方向。",
        "breadcrumb_items": [
            {"label": "学生课程页", "href": "/student/courses"},
            {"label": "C++"},
        ],
        "summary_cards": [
            {"label": "已开放", "value": "GESP"},
            {"label": "体验中", "value": "机器人编程"},
            {"label": "未开放", "value": "CSP"},
        ],
        "entry_hint": "从这里进入 C++ 的下一层。",
        "portal_cards": [
            {
                "slug": "gesp",
                "title": "GESP",
                "meta": "等级路径",
                "subtitle": "已开放入口",
                "note": "继续进入 GESP1 - GESP4",
                "state": "open",
                "status_text": "已开放",
                "featured": True,
                "action_label": "进入 GESP",
                "action_href": "/student/cpp/gesp",
            },
            {
                "slug": "csp",
                "title": "CSP",
                "meta": "竞赛进阶",
                "subtitle": "结构预留",
                "note": "分类入口预留",
                "state": "locked",
                "status_text": "未开放",
            },
            {
                "slug": "robotics",
                "title": "机器人编程",
                "meta": "硬件与控制",
                "subtitle": "体验预留",
                "note": "后续扩展内容",
                "state": "trial",
                "status_text": "体验中",
                "action_label": "查看预留",
                "action_href": "#cpp-robotics",
            },
        ],
    },
    "cpp_gesp": {
        "page_mode": "entry_grid",
        "grid_variant": "levels",
        "hero_eyebrow": "GESP Learning Portal",
        "page_title": "GESP 学习层级页",
        "page_description": "请选择一个 GESP 层级。",
        "breadcrumb_items": [
            {"label": "学生课程页", "href": "/student/courses"},
            {"label": "C++", "href": "/student/cpp"},
            {"label": "GESP"},
        ],
        "summary_cards": [
            {"label": "当前层级", "value": "4 级"},
            {"label": "重点入口", "value": "GESP4"},
            {"label": "锁定中", "value": "3 级"},
        ],
        "entry_hint": "GESP4 已预留，其余层级先占位。",
        "portal_cards": [
            {
                "slug": "gesp1",
                "title": "GESP1",
                "meta": "Level 1",
                "subtitle": "入门基础",
                "note": "当前未开放",
                "state": "locked",
                "status_text": "未开放",
            },
            {
                "slug": "gesp2",
                "title": "GESP2",
                "meta": "Level 2",
                "subtitle": "基础巩固",
                "note": "当前未开放",
                "state": "locked",
                "status_text": "未开放",
            },
            {
                "slug": "gesp3",
                "title": "GESP3",
                "meta": "Level 3",
                "subtitle": "进阶过渡",
                "note": "当前未开放",
                "state": "locked",
                "status_text": "未开放",
            },
            {
                "slug": "gesp4",
                "title": "GESP4",
                "meta": "Level 4",
                "subtitle": "真实内容入口预留",
                "note": "后续接入二维数组专题",
                "state": "open",
                "status_text": "重点预留",
                "featured": True,
                "action_label": "进入 GESP4",
                "action_href": "/student/cpp/gesp/gesp4",
            },
        ],
    },
    "cpp_gesp4": {
        "hero_eyebrow": "GESP4 Reserved Entry",
        "page_title": "GESP4 真实内容入口预留",
        "page_description": "这里不是旧专题页面本体，而是为未来接入第一个真实课程内容预留的入口层。",
        "breadcrumb_items": [
            {"label": "学生课程页", "href": "/student/courses"},
            {"label": "C++", "href": "/student/cpp"},
            {"label": "GESP", "href": "/student/cpp/gesp"},
            {"label": "GESP4"},
        ],
        "summary_cards": [
            {"label": "当前层级", "value": "GESP4", "hint": "首个真实内容承接层"},
            {"label": "预留专题", "value": "1 个", "hint": "二维数组专题将优先接入"},
            {"label": "当前状态", "value": "仅预留", "hint": "本批次不接入旧项目本体"},
        ],
        "section_eyebrow": "Reserved Entry",
        "section_title": "首个真实内容入口预留",
        "section_description": "这一页只负责把未来真实内容入口位置固定下来，让后续接入时有清晰的层级承接点。",
        "portal_notice": {
            "title": "当前预留说明",
            "description": "本页只展示入口结构、学习路径和接入提示，不包含旧二维数组项目代码，也不展开真实业务内容。",
            "items": [
                "当前路径已固定为：C++ > GESP > GESP4 > 二维数组专题",
                "本页只保留内容接入位置，不提供真实课程逻辑",
                "下一步可在此挂接专题首页或专题目录页",
            ],
        },
        "page_mode": "reserved",
        "reserved_entry": {
            "label": "第一个真实内容入口",
            "status_text": "待接入",
            "path": ["C++", "GESP", "GESP4", "二维数组专题"],
            "title": "二维数组专题",
            "description": "未来系统的第一个真实课程内容将优先接在这里。当前只保留入口壳子与路径语义，确保后续接入时无需重做学生端层级结构。",
        },
        "reserved_notes": [
            {
                "title": "当前作用",
                "description": "固定真实内容入口位置，让学生端层级路径先成立。",
            },
            {
                "title": "后续接法",
                "description": "下一步可以在这里接入专题首页、专题目录或专题详情的真实页面。",
            },
            {
                "title": "当前边界",
                "description": "本页不引入旧项目代码、不接数据库、不做真实开放逻辑。",
            },
        ],
        "support_label": "Entry Notes",
        "support_title": "入口预留说明",
        "support_description": "右侧说明帮助明确这个页面只是接入口，而不是已经接好的真实专题。",
        "support_items": [
            {"title": "入口已固定", "description": "学生层级已明确落到 GESP4，再继续承接真实专题。"},
            {"title": "专题未接入", "description": "旧二维数组项目本体仍然留到下一步单独接入。"},
            {"title": "壳子先行", "description": "这一步优先保证学生端学习路径和产品语义成立。"},
        ],
    },
}
