from django.urls import path

from .views import (
    login_page,
    logout_view,
    parent_homework_detail,
    parent_homework_list,
    parent_homework_print,
    parent_homework_print_blank,
    parent_homework_summary_detail,
    parent_homework_print_wrong,
    parent_homework_submission_detail,
    parent_student_profile,
    principal_dashboard,
    student_account_settings,
    student_cpp,
    student_cpp_gesp,
    student_cpp_gesp2,
    student_cpp_gesp2_topic,
    student_cpp_gesp4,
    student_cpp_gesp4_array_2d,
    student_cpp_gesp4_topic,
    student_courses,
    student_homework_detail,
    student_homework_list,
    student_homework_practice,
    student_homework_print,
    student_homework_print_blank,
    student_homework_print_wrong,
    student_homework_summary_detail,
    student_homework_submission_detail,
    student_practice,
    teacher_cpp_gesp2_ascii_char_encoding,
    teacher_cpp_gesp2_enumeration,
    teacher_cpp_gesp4_array_2d,
    teacher_cpp_gesp4_binary_search,
    teacher_cpp_gesp4_sorting,
    teacher_cpp_gesp4_strings,
    teacher_course_category_detail,
    teacher_course_detail,
    teacher_course_export,
    teacher_course_student_pool,
    teacher_course_category_export,
    teacher_course_knowledge_point_delete,
    teacher_course_knowledge_point_edit,
    teacher_course_knowledge_point_new,
    teacher_course_knowledge_point_permissions,
    teacher_course_knowledge_point_teaching_page,
    teacher_course_level_detail,
    teacher_course_level_export,
    teacher_course_students_detail,
    teacher_question_manual_override,
    teacher_assignment_new,
    teacher_homework_builder,
    teacher_student_assignment_edit,
    teacher_student_assignment_remove,
    teacher_student_assignments,
    teacher_student_detail,
    teacher_students,
)


urlpatterns = [
    path("", login_page, name="login"),
    path("logout", logout_view, name="logout"),
    path("student/courses", student_courses, name="student-courses"),
    path("student/practice", student_practice, name="student-practice"),
    path("student/practice/homework", student_homework_list, name="student-homework-list"),
    path("student/practice/homework/<int:assignment_id>", student_homework_detail, name="student-homework-detail"),
    path(
        "student/practice/homework/<int:assignment_id>/summary",
        student_homework_summary_detail,
        name="student-homework-summary",
    ),
    path("student/practice/homework/<int:assignment_id>/practice", student_homework_practice, name="student-homework-practice"),
    path(
        "student/practice/homework/<int:assignment_id>/submissions/<int:submission_id>",
        student_homework_submission_detail,
        name="student-homework-submission-detail",
    ),
    path(
        "student/practice/homework/<int:assignment_id>/submissions/<int:submission_id>/print",
        student_homework_print,
        name="student-homework-print",
    ),
    path(
        "student/practice/homework/<int:assignment_id>/submissions/<int:submission_id>/print/wrong",
        student_homework_print_wrong,
        name="student-homework-print-wrong",
    ),
    path(
        "student/practice/homework/<int:assignment_id>/print/blank",
        student_homework_print_blank,
        name="student-homework-print-blank",
    ),
    path("student/account-settings", student_account_settings, name="student-account-settings"),
    path("student/cpp", student_cpp, name="student-cpp"),
    path("student/cpp/gesp", student_cpp_gesp, name="student-cpp-gesp"),
    path("student/cpp/gesp/gesp2", student_cpp_gesp2, name="student-cpp-gesp2"),
    path("student/cpp/gesp/gesp2/<slug:topic_slug>", student_cpp_gesp2_topic, name="student-cpp-gesp2-topic"),
    path("student/cpp/gesp/gesp4", student_cpp_gesp4, name="student-cpp-gesp4"),
    path("student/cpp/gesp/gesp4/array-2d", student_cpp_gesp4_array_2d, name="student-cpp-gesp4-array-2d"),
    path("student/cpp/gesp/gesp4/<slug:topic_slug>", student_cpp_gesp4_topic, name="student-cpp-gesp4-topic"),
    path("parent/student-profile", parent_student_profile, name="parent-student-profile"),
    path("parent/student-profile/homework", parent_homework_list, name="parent-homework-list"),
    path("parent/student-profile/homework/<int:assignment_id>", parent_homework_detail, name="parent-homework-detail"),
    path(
        "parent/student-profile/homework/<int:assignment_id>/summary",
        parent_homework_summary_detail,
        name="parent-homework-summary",
    ),
    path(
        "parent/student-profile/homework/<int:assignment_id>/submissions/<int:submission_id>",
        parent_homework_submission_detail,
        name="parent-homework-submission-detail",
    ),
    path(
        "parent/student-profile/homework/<int:assignment_id>/submissions/<int:submission_id>/print",
        parent_homework_print,
        name="parent-homework-print",
    ),
    path(
        "parent/student-profile/homework/<int:assignment_id>/submissions/<int:submission_id>/print/wrong",
        parent_homework_print_wrong,
        name="parent-homework-print-wrong",
    ),
    path(
        "parent/student-profile/homework/<int:assignment_id>/print/blank",
        parent_homework_print_blank,
        name="parent-homework-print-blank",
    ),
    path("teacher/students", teacher_students, name="teacher-students"),
    path("teacher/students/assignments/new", teacher_assignment_new, name="teacher-assignment-new"),
    path(
        "teacher/students/<int:student_id>/assignments/<int:assignment_id>/edit",
        teacher_student_assignment_edit,
        name="teacher-student-assignment-edit",
    ),
    path(
        "teacher/students/<int:student_id>/assignments/<int:assignment_id>/remove",
        teacher_student_assignment_remove,
        name="teacher-student-assignment-remove",
    ),
    path(
        "teacher/students/<int:student_id>/assignments",
        teacher_student_assignments,
        name="teacher-student-assignments",
    ),
    path(
        "teacher/courses/cpp/gesp2/ascii-char-encoding",
        teacher_cpp_gesp2_ascii_char_encoding,
        name="teacher-cpp-gesp2-ascii-char-encoding",
    ),
    path("teacher/courses/cpp/gesp2/enumeration-method", teacher_cpp_gesp2_enumeration, name="teacher-cpp-gesp2-enumeration"),
    path(
        "teacher/questions/<int:question_id>/manual-override",
        teacher_question_manual_override,
        name="teacher-question-manual-override",
    ),
    path("teacher/courses/cpp/gesp4/array-2d", teacher_cpp_gesp4_array_2d, name="teacher-cpp-gesp4-array-2d"),
    path("teacher/courses/cpp/gesp4/binary-search", teacher_cpp_gesp4_binary_search, name="teacher-cpp-gesp4-binary-search"),
    path("teacher/courses/cpp/gesp4/sorting", teacher_cpp_gesp4_sorting, name="teacher-cpp-gesp4-sorting"),
    path("teacher/courses/cpp/gesp4/strings", teacher_cpp_gesp4_strings, name="teacher-cpp-gesp4-strings"),
    path(
        "teacher/courses/<slug:course_slug>/categories/<slug:category_slug>/levels/<slug:level_code>/knowledge-points/new",
        teacher_course_knowledge_point_new,
        name="teacher-course-knowledge-point-new",
    ),
    path(
        "teacher/courses/<slug:course_slug>/categories/<slug:category_slug>/levels/<slug:level_code>/knowledge-points/<slug:content_slug>/permissions",
        teacher_course_knowledge_point_permissions,
        name="teacher-course-knowledge-point-permissions",
    ),
    path(
        "teacher/courses/<slug:course_slug>/categories/<slug:category_slug>/levels/<slug:level_code>/knowledge-points/<slug:content_slug>/teaching-page",
        teacher_course_knowledge_point_teaching_page,
        name="teacher-course-knowledge-point-teaching-page",
    ),
    path(
        "teacher/courses/<slug:course_slug>/categories/<slug:category_slug>/levels/<slug:level_code>/knowledge-points/<slug:content_slug>/edit",
        teacher_course_knowledge_point_edit,
        name="teacher-course-knowledge-point-edit",
    ),
    path(
        "teacher/courses/<slug:course_slug>/categories/<slug:category_slug>/levels/<slug:level_code>/knowledge-points/<slug:content_slug>/delete",
        teacher_course_knowledge_point_delete,
        name="teacher-course-knowledge-point-delete",
    ),
    path(
        "teacher/courses/<slug:course_slug>/categories/<slug:category_slug>/levels/<slug:level_code>",
        teacher_course_level_detail,
        name="teacher-course-level-detail",
    ),
    path(
        "teacher/courses/<slug:course_slug>/categories/<slug:category_slug>/levels/<slug:level_code>/export",
        teacher_course_level_export,
        name="teacher-course-level-export",
    ),
    path(
        "teacher/courses/<slug:course_slug>/categories/<slug:category_slug>",
        teacher_course_category_detail,
        name="teacher-course-category-detail",
    ),
    path(
        "teacher/courses/<slug:course_slug>/categories/<slug:category_slug>/export",
        teacher_course_category_export,
        name="teacher-course-category-export",
    ),
    path("teacher/courses/<slug:course_slug>/students", teacher_course_students_detail, name="teacher-course-students-detail"),
    path("teacher/courses/<slug:course_slug>/student-pool", teacher_course_student_pool, name="teacher-course-student-pool"),
    path("teacher/courses/<slug:course_slug>/export", teacher_course_export, name="teacher-course-export"),
    path("teacher/courses/<slug:course_slug>", teacher_course_detail, name="teacher-course-detail"),
    path(
        "teacher/students/<int:student_id>/homework/<int:assignment_id>",
        teacher_homework_builder,
        name="teacher-homework-builder",
    ),
    path("teacher/students/<int:student_id>", teacher_student_detail, name="teacher-student-detail"),
    path("principal/dashboard", principal_dashboard, name="principal-dashboard"),
]
