# Generated by Django 5.2.12 on 2026-04-06 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='课程标识')),
                ('title', models.CharField(max_length=64, verbose_name='课程名称')),
                ('summary', models.TextField(blank=True, verbose_name='课程说明')),
            ],
            options={
                'verbose_name': '课程方向',
                'verbose_name_plural': '课程方向',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PortalUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, unique=True, verbose_name='账号')),
                ('password', models.CharField(default='123456', max_length=128, verbose_name='密码')),
                ('role', models.CharField(choices=[('student', '学生'), ('parent', '家长'), ('teacher', '教师'), ('principal', '校长')], max_length=20, verbose_name='角色')),
                ('full_name', models.CharField(max_length=64, verbose_name='姓名')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '账号',
                'verbose_name_plural': '账号',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CourseContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='内容标识')),
                ('title', models.CharField(max_length=128, verbose_name='内容名称')),
                ('phase', models.CharField(blank=True, max_length=64, verbose_name='所属阶段')),
                ('route_path', models.CharField(max_length=255, unique=True, verbose_name='访问路由')),
                ('summary', models.TextField(blank=True, verbose_name='内容说明')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='entry.course')),
            ],
            options={
                'verbose_name': '课程内容',
                'verbose_name_plural': '课程内容',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=64, verbose_name='学生姓名')),
                ('grade', models.CharField(max_length=32, verbose_name='年级')),
                ('campus', models.CharField(blank=True, max_length=64, verbose_name='校区')),
                ('current_program', models.CharField(blank=True, max_length=64, verbose_name='当前方向')),
                ('phase_label', models.CharField(blank=True, max_length=64, verbose_name='阶段标签')),
                ('parent_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='entry.portaluser')),
                ('teacher_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_students', to='entry.portaluser')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to='entry.portaluser')),
            ],
            options={
                'verbose_name': '学生',
                'verbose_name_plural': '学生',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='StudentContentAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_open', models.BooleanField(default=False, verbose_name='是否开放')),
                ('granted_at', models.DateTimeField(blank=True, null=True, verbose_name='开放时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_accesses', to='entry.coursecontent')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_content_accesses', to='entry.portaluser')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_accesses', to='entry.student')),
            ],
            options={
                'verbose_name': '学生内容开放记录',
                'verbose_name_plural': '学生内容开放记录',
                'ordering': ['id'],
                'unique_together': {('student', 'content')},
            },
        ),
    ]
