# Generated by Django 5.2.12 on 2026-04-07 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0003_expand_gesp4_topics'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonHourLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta_hours', models.IntegerField(verbose_name='课时变动')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_hour_ledgers', to='entry.student')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_lesson_hour_ledgers', to='entry.portaluser')),
            ],
            options={
                'verbose_name': '课时变动记录',
                'verbose_name_plural': '课时变动记录',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RewardRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_text', models.CharField(max_length=255, verbose_name='奖励说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_records', to='entry.student')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_rewards', to='entry.portaluser')),
            ],
            options={
                'verbose_name': '奖励记录',
                'verbose_name_plural': '奖励记录',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TeacherEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_text', models.TextField(verbose_name='教师评价')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_evaluations', to='entry.student')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_evaluations', to='entry.portaluser')),
            ],
            options={
                'verbose_name': '教师评价',
                'verbose_name_plural': '教师评价',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
