# Generated by Django 5.2.12 on 2026-04-07 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0004_lessonhourledger_rewardrecord_teacherevaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='portaluser',
            name='phone',
            field=models.CharField(blank=True, max_length=32, verbose_name='手机号'),
        ),
    ]
