# Generated by Django 5.2.12 on 2026-04-16 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0016_homework_online_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworkimportjob',
            name='source_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('image', '图片'), ('html', 'HTML'), ('text', 'TXT'), ('docx', 'DOCX'), ('xlsx', 'XLSX')], max_length=16, verbose_name='源文件类型'),
        ),
    ]
