# Generated by Django 5.2.12 on 2026-04-22 09:37

from django.db import migrations, models


CPP_STAGE_PERMISSION_CODE_MAP = {
    "GESP1": "C1",
    "GESP2": "C1",
    "GESP3": "C1",
    "GESP4": "C1",
    "GESP5": "C2",
    "GESP6": "C2",
    "GESP7": "C2",
    "GESP8": "C2",
    "CSP-J": "C3",
    "CSPJ": "C3",
    "CSP-S": "C4",
    "CSPS": "C4",
}


def normalize_stage_code(value):
    normalized = (value or "").strip().upper()
    normalized = normalized.replace("—", "-").replace("–", "-").replace("_", "-")
    normalized = normalized.replace(" ", "")
    return normalized


def infer_permission_code(course_slug, level_code="", phase=""):
    if course_slug != "cpp":
        return ""
    for candidate in (level_code, phase):
        normalized = normalize_stage_code(candidate)
        if normalized in {"C1", "C2", "C3", "C4"}:
            return normalized
        mapped_code = CPP_STAGE_PERMISSION_CODE_MAP.get(normalized)
        if mapped_code:
            return mapped_code
    return ""


def backfill_permission_code_and_cleanup_accesses(apps, schema_editor):
    CourseContent = apps.get_model("entry", "CourseContent")
    StudentContentAccess = apps.get_model("entry", "StudentContentAccess")

    for content in CourseContent.objects.select_related("course", "level").all():
        level_code = content.level.code if getattr(content, "level_id", None) and content.level else ""
        permission_code = infer_permission_code(
            getattr(content.course, "slug", ""),
            level_code=level_code,
            phase=getattr(content, "phase", ""),
        )
        if permission_code and getattr(content, "permission_code", "") != permission_code:
            CourseContent.objects.filter(id=content.id).update(permission_code=permission_code)

    # 历史上 `is_open=False` 是 allowlist 默认值的副产物，进入 override 模式后要清空这批噪音记录。
    StudentContentAccess.objects.filter(is_open=False).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0019_homeworksubmission_multiple_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecontent',
            name='permission_code',
            field=models.CharField(blank=True, choices=[('C1', 'C1'), ('C2', 'C2'), ('C3', 'C3'), ('C4', 'C4')], default='', max_length=4, verbose_name='权限归属'),
        ),
        migrations.AddIndex(
            model_name='coursecontent',
            index=models.Index(fields=['permission_code', 'is_active', 'sort_order'], name='content_perm_active_sort_idx'),
        ),
        migrations.RunPython(backfill_permission_code_and_cleanup_accesses, migrations.RunPython.noop),
    ]
