# Generated by Django 5.2.12 on 2026-04-23 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entry", "0020_coursecontent_permission_code_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomeworkSummary",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(blank=True, default="", max_length=255, verbose_name="总结标题")),
                ("summary_html", models.TextField(blank=True, default="", verbose_name="总结 HTML")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "assignment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="summary",
                        to="entry.homeworkassignment",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_homework_summaries",
                        to="entry.portaluser",
                    ),
                ),
            ],
            options={
                "verbose_name": "作业周总结",
                "verbose_name_plural": "作业周总结",
                "ordering": ["-updated_at", "-id"],
            },
        ),
    ]
