# Generated by Django 5.2.12 on 2026-04-23 11:00

import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone


def backfill_assignment_summary_fk(apps, schema_editor):
    HomeworkAssignment = apps.get_model("entry", "HomeworkAssignment")
    HomeworkSummary = apps.get_model("entry", "HomeworkSummary")

    for summary in HomeworkSummary.objects.exclude(assignment_id=None).iterator():
        HomeworkAssignment.objects.filter(id=summary.assignment_id).update(
            summary_id=summary.id,
            updated_at=timezone.now(),
        )


class Migration(migrations.Migration):

    dependencies = [
        ("entry", "0021_homeworksummary"),
    ]

    operations = [
        migrations.AddField(
            model_name="homeworkassignment",
            name="summary",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assignments",
                to="entry.homeworksummary",
            ),
        ),
        migrations.RunPython(backfill_assignment_summary_fk, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="homeworksummary",
            name="assignment",
        ),
    ]
