# Generated by Django 5.2.12 on 2026-04-24 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entry", "0022_homeworksummary_assignment_fk"),
    ]

    operations = [
        migrations.AddField(
            model_name="homeworkassignment",
            name="source_import_job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shared_assignments",
                to="entry.homeworkimportjob",
            ),
        ),
    ]
