# Generated by Django 5.2.12 on 2026-05-03 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0023_homeworkassignment_source_import_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworkimportjob',
            name='content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homework_import_jobs', to='entry.coursecontent'),
        ),
        migrations.AlterField(
            model_name='homeworkimportjob',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='import_jobs', to='entry.homeworkassignment'),
        ),
        migrations.AlterField(
            model_name='homeworkquestion',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='entry.homeworkassignment'),
        ),
    ]
