# Generated by Django 5.2.12 on 2026-05-04 05:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0024_homeworkimportjob_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeworkCompletionStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('week', '本周'), ('month', '本月'), ('quarter', '本季度')], max_length=16, verbose_name='周期类型')),
                ('period_start', models.DateField(verbose_name='周期开始日期')),
                ('period_end', models.DateField(verbose_name='周期结束日期')),
                ('completed_count', models.PositiveIntegerField(default=0, verbose_name='已完成数量')),
                ('incomplete_count', models.PositiveIntegerField(default=0, verbose_name='未完成数量')),
                ('excluded_undated_count', models.PositiveIntegerField(default=0, verbose_name='排除的无截止日期数量')),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='统计生成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_completion_stats', to='entry.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_completion_stats', to='entry.portaluser')),
            ],
            options={
                'verbose_name': '作业完成统计',
                'verbose_name_plural': '作业完成统计',
                'ordering': ['period_start', 'period_type', 'teacher_id', 'student_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HomeworkCompletionStatMissingAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, choices=[('online_missing', '在线题未形成完成态提交'), ('requirement_not_marked_completed', '要求型作业未标记完成'), ('undated', '无截止日期')], default='', max_length=48, verbose_name='未完成原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completion_stat_missing_links', to='entry.homeworkassignment')),
                ('stat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missing_assignments', to='entry.homeworkcompletionstat')),
            ],
            options={
                'verbose_name': '作业完成统计未完成作业',
                'verbose_name_plural': '作业完成统计未完成作业',
                'ordering': ['stat_id', 'assignment_id', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='homeworkcompletionstat',
            index=models.Index(fields=['teacher', 'period_type', 'period_start', 'period_end'], name='hwc_stat_teacher_pd_idx'),
        ),
        migrations.AddIndex(
            model_name='homeworkcompletionstat',
            index=models.Index(fields=['student', 'period_type', 'period_start', 'period_end'], name='hwc_stat_student_pd_idx'),
        ),
        migrations.AddConstraint(
            model_name='homeworkcompletionstat',
            constraint=models.UniqueConstraint(fields=('teacher', 'student', 'period_type', 'period_start', 'period_end'), name='hw_completion_stat_unique'),
        ),
        migrations.AddConstraint(
            model_name='homeworkcompletionstatmissingassignment',
            constraint=models.UniqueConstraint(fields=('stat', 'assignment'), name='hw_comp_stat_missing_unique'),
        ),
    ]
