# Generated by Django 5.2.12 on 2026-05-04 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0025_homeworkcompletionstat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworksummary',
            name='areas_for_growth',
            field=models.TextField(blank=True, default='', verbose_name='待提升点'),
        ),
        migrations.AddField(
            model_name='homeworksummary',
            name='highlights',
            field=models.TextField(blank=True, default='', verbose_name='亮点表现'),
        ),
    ]
