# Generated by Django 5.2.12 on 2026-05-06 05:22

from django.db import migrations, models


def _column_exists(schema_editor, table_name: str, column_name: str) -> bool:
    with schema_editor.connection.cursor() as cursor:
        table_description = schema_editor.connection.introspection.get_table_description(
            cursor,
            table_name,
        )
    return any(column.name == column_name for column in table_description)


def _drop_column_if_exists(schema_editor, table_name: str, column_name: str) -> None:
    if not _column_exists(schema_editor, table_name, column_name):
        return
    quoted_table = schema_editor.quote_name(table_name)
    quoted_column = schema_editor.quote_name(column_name)
    schema_editor.execute(f"ALTER TABLE {quoted_table} DROP COLUMN {quoted_column}")


def _add_text_column_if_missing(schema_editor, table_name: str, column_name: str) -> None:
    if _column_exists(schema_editor, table_name, column_name):
        return
    quoted_table = schema_editor.quote_name(table_name)
    quoted_column = schema_editor.quote_name(column_name)
    schema_editor.execute(
        f"ALTER TABLE {quoted_table} ADD COLUMN {quoted_column} text NOT NULL DEFAULT ''"
    )


def forwards(apps, schema_editor) -> None:
    _drop_column_if_exists(schema_editor, "entry_homeworksummary", "areas_for_growth")
    _drop_column_if_exists(schema_editor, "entry_homeworksummary", "highlights")
    _add_text_column_if_missing(schema_editor, "entry_homeworkassignment", "areas_for_growth")
    _add_text_column_if_missing(schema_editor, "entry_homeworkassignment", "highlights")


def backwards(apps, schema_editor) -> None:
    _drop_column_if_exists(schema_editor, "entry_homeworkassignment", "areas_for_growth")
    _drop_column_if_exists(schema_editor, "entry_homeworkassignment", "highlights")
    _add_text_column_if_missing(schema_editor, "entry_homeworksummary", "areas_for_growth")
    _add_text_column_if_missing(schema_editor, "entry_homeworksummary", "highlights")


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0026_homeworksummary_areas_for_growth_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(forwards, backwards),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name='homeworksummary',
                    name='areas_for_growth',
                ),
                migrations.RemoveField(
                    model_name='homeworksummary',
                    name='highlights',
                ),
                migrations.AddField(
                    model_name='homeworkassignment',
                    name='areas_for_growth',
                    field=models.TextField(blank=True, default='', verbose_name='待提升点'),
                ),
                migrations.AddField(
                    model_name='homeworkassignment',
                    name='highlights',
                    field=models.TextField(blank=True, default='', verbose_name='亮点表现'),
                ),
            ],
        ),
    ]
