# Generated by Django 5.2.12 on 2026-05-13 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0028_alter_homeworkassignment_due_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentOjWeeklyStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='dashima-oj', max_length=64)),
                ('oj_username', models.CharField(blank=True, max_length=128)),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('submission_count', models.PositiveIntegerField(default=0, verbose_name='本周 OJ 提交数量')),
                ('accepted_count', models.PositiveIntegerField(default=0, verbose_name='本周 OJ 通过数量')),
                ('raw_record_count', models.PositiveIntegerField(default=0, verbose_name='本次拉取原始记录数')),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oj_weekly_stats', to='entry.student')),
            ],
            options={
                'verbose_name': '学生 OJ 周统计',
                'verbose_name_plural': '学生 OJ 周统计',
                'ordering': ['-week_start', 'student_id', 'source'],
                'indexes': [models.Index(fields=['source', 'week_start'], name='oj_stat_source_week_idx'), models.Index(fields=['student', 'week_start'], name='oj_stat_student_week_idx'), models.Index(fields=['oj_username'], name='oj_stat_username_idx')],
                'constraints': [models.UniqueConstraint(fields=('student', 'source', 'week_start'), name='uniq_student_oj_weekly_stat')],
            },
        ),
    ]
