# Generated by Django 5.2.12 on 2026-05-16 03:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0029_studentojweeklystat'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassroomLiveParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('teacher', '老师'), ('student', '学生')], max_length=16, verbose_name='课堂角色')),
                ('livekit_identity', models.CharField(max_length=128, verbose_name='LiveKit 身份')),
                ('connection_state', models.CharField(choices=[('invited', '待加入'), ('joined', '已加入'), ('left', '已离开')], default='invited', max_length=16, verbose_name='连接状态')),
                ('screen_state', models.CharField(choices=[('none', '未投屏'), ('pending', '等待投屏'), ('sharing', '投屏中'), ('stopped', '已停止'), ('rejected', '已拒绝')], default='none', max_length=16, verbose_name='投屏状态')),
                ('display_surface', models.CharField(blank=True, max_length=32, verbose_name='共享屏幕类型')),
                ('joined_at', models.DateTimeField(blank=True, null=True, verbose_name='加入时间')),
                ('left_at', models.DateTimeField(blank=True, null=True, verbose_name='离开时间')),
                ('screen_started_at', models.DateTimeField(blank=True, null=True, verbose_name='投屏开始时间')),
                ('screen_stopped_at', models.DateTimeField(blank=True, null=True, verbose_name='投屏停止时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('portal_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_live_participants', to='entry.portaluser')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classroom_live_participants', to='entry.student')),
            ],
            options={
                'verbose_name': '实时课堂成员',
                'verbose_name_plural': '实时课堂成员',
                'ordering': ['role', 'joined_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ClassroomLiveSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=128, verbose_name='课堂标题')),
                ('status', models.CharField(choices=[('active', '上课中'), ('ended', '已下课'), ('failed', '异常结束')], default='active', max_length=16, verbose_name='课堂状态')),
                ('workspace_type', models.CharField(choices=[('screen_share', '屏幕共享')], default='screen_share', max_length=32, verbose_name='工作区类型')),
                ('livekit_room_name', models.CharField(max_length=128, unique=True, verbose_name='LiveKit 房间名')),
                ('view_mode', models.CharField(choices=[('normal', '常规视图'), ('spotlight_student', '学生主屏'), ('split_compare', '并列对比')], default='normal', max_length=32, verbose_name='老师视图模式')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='开始时间')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('pinned_participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pinned_sessions', to='entry.classroomliveparticipant')),
                ('spotlight_participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spotlight_sessions', to='entry.classroomliveparticipant')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_live_sessions', to='entry.portaluser')),
            ],
            options={
                'verbose_name': '实时课堂',
                'verbose_name_plural': '实时课堂',
                'ordering': ['-started_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ClassroomLiveRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('livekit_egress', 'LiveKit Egress'), ('browser_audio', '浏览器录音')], default='livekit_egress', max_length=32, verbose_name='录制服务')),
                ('status', models.CharField(choices=[('starting', '启动中'), ('active', '录制中'), ('completed', '已完成'), ('failed', '失败')], default='starting', max_length=16, verbose_name='录制状态')),
                ('egress_id', models.CharField(blank=True, max_length=128, verbose_name='LiveKit Egress ID')),
                ('file_url', models.URLField(blank=True, max_length=500, verbose_name='录制文件 URL')),
                ('file_path', models.CharField(blank=True, max_length=500, verbose_name='录制文件路径')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='开始时间')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='entry.classroomlivesession')),
            ],
            options={
                'verbose_name': '实时课堂录制',
                'verbose_name_plural': '实时课堂录制',
                'ordering': ['-started_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='classroomliveparticipant',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='entry.classroomlivesession'),
        ),
        migrations.AddIndex(
            model_name='classroomlivesession',
            index=models.Index(fields=['teacher', 'status', '-started_at'], name='cls_teacher_status_started_idx'),
        ),
        migrations.AddIndex(
            model_name='classroomlivesession',
            index=models.Index(fields=['status', '-started_at'], name='cls_status_started_idx'),
        ),
        migrations.AddConstraint(
            model_name='classroomlivesession',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('teacher',), name='uniq_active_classroom_session_per_teacher'),
        ),
        migrations.AddIndex(
            model_name='classroomliverecording',
            index=models.Index(fields=['session', 'status'], name='clr_session_status_idx'),
        ),
        migrations.AddIndex(
            model_name='classroomliverecording',
            index=models.Index(fields=['egress_id'], name='clr_egress_id_idx'),
        ),
        migrations.AddConstraint(
            model_name='classroomliverecording',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['starting', 'active'])), fields=('session',), name='uniq_active_classroom_recording_per_session'),
        ),
        migrations.AddIndex(
            model_name='classroomliveparticipant',
            index=models.Index(fields=['session', 'role'], name='clp_session_role_idx'),
        ),
        migrations.AddIndex(
            model_name='classroomliveparticipant',
            index=models.Index(fields=['student', 'connection_state'], name='clp_student_connection_idx'),
        ),
        migrations.AddIndex(
            model_name='classroomliveparticipant',
            index=models.Index(fields=['portal_user', 'connection_state'], name='clp_user_connection_idx'),
        ),
        migrations.AddConstraint(
            model_name='classroomliveparticipant',
            constraint=models.UniqueConstraint(fields=('session', 'portal_user'), name='uniq_classroom_participant_user'),
        ),
        migrations.AddConstraint(
            model_name='classroomliveparticipant',
            constraint=models.UniqueConstraint(fields=('session', 'livekit_identity'), name='uniq_classroom_participant_identity'),
        ),
    ]
