# Generated by Django 5.2.12 on 2026-05-21 06:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0032_live_recording_browser_screen'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassroomLiveActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('single_choice', '选择题'), ('true_false', '判断题')], max_length=32, verbose_name='题型')),
                ('title', models.CharField(max_length=128, verbose_name='标题')),
                ('prompt_text', models.TextField(verbose_name='题面')),
                ('options_json', models.JSONField(blank=True, default=dict, verbose_name='选项')),
                ('correct_answer', models.CharField(blank=True, max_length=16, verbose_name='正确答案')),
                ('status', models.CharField(choices=[('published', '进行中'), ('closed', '已关闭')], default='published', max_length=16, verbose_name='状态')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='发布时间')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='关闭时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='entry.classroomlivesession')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_live_activities', to='entry.portaluser')),
            ],
            options={
                'verbose_name': '实时课堂任务',
                'verbose_name_plural': '实时课堂任务',
                'ordering': ['-published_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ClassroomLiveActivityResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=16, verbose_name='答案')),
                ('is_correct', models.BooleanField(blank=True, null=True, verbose_name='是否正确')),
                ('correct_answer_snapshot', models.CharField(blank=True, max_length=16, verbose_name='正确答案快照')),
                ('attempt_no', models.PositiveIntegerField(default=1, verbose_name='提交次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='entry.classroomliveactivity')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_responses', to='entry.classroomliveparticipant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_responses', to='entry.classroomlivesession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_live_activity_responses', to='entry.student')),
            ],
            options={
                'verbose_name': '实时课堂答题记录',
                'verbose_name_plural': '实时课堂答题记录',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='classroomliveactivity',
            index=models.Index(fields=['session', 'status', '-published_at'], name='cla_session_status_pub_idx'),
        ),
        migrations.AddIndex(
            model_name='classroomliveactivity',
            index=models.Index(fields=['teacher', '-published_at'], name='cla_teacher_pub_idx'),
        ),
        migrations.AddConstraint(
            model_name='classroomliveactivity',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'published')), fields=('session',), name='uniq_published_live_activity_per_session'),
        ),
        migrations.AddIndex(
            model_name='classroomliveactivityresponse',
            index=models.Index(fields=['activity', 'student', '-created_at'], name='clar_activity_student_idx'),
        ),
        migrations.AddIndex(
            model_name='classroomliveactivityresponse',
            index=models.Index(fields=['session', 'student', '-created_at'], name='clar_session_student_idx'),
        ),
        migrations.AddIndex(
            model_name='classroomliveactivityresponse',
            index=models.Index(fields=['activity', 'answer'], name='clar_activity_answer_idx'),
        ),
    ]
