# Generated by Django 5.2.12 on 2026-06-02 07:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0033_classroomliveactivity_classroomliveactivityresponse_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='考试标题')),
                ('description', models.TextField(blank=True, verbose_name='考试说明')),
                ('duration_minutes', models.PositiveIntegerField(default=60, verbose_name='考试时长（分钟）')),
                ('start_at', models.DateTimeField(blank=True, null=True, verbose_name='允许开始时间')),
                ('end_at', models.DateTimeField(blank=True, null=True, verbose_name='截止时间')),
                ('proctoring_enabled', models.BooleanField(default=False, verbose_name='是否开启监考记录')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('archived', '已归档')], default='draft', max_length=16, verbose_name='状态')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_papers', to='entry.course')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_papers', to='entry.portaluser')),
            ],
            options={
                'verbose_name': '考试试卷',
                'verbose_name_plural': '考试试卷',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_no', models.PositiveIntegerField(verbose_name='题号')),
                ('question_type', models.CharField(choices=[('single_choice', '单选题')], default='single_choice', max_length=32, verbose_name='题型')),
                ('stem', models.TextField(verbose_name='题干')),
                ('options_json', models.JSONField(blank=True, default=dict, verbose_name='选项')),
                ('correct_answer', models.CharField(max_length=1, verbose_name='正确答案')),
                ('analysis', models.TextField(blank=True, verbose_name='解析')),
                ('score', models.DecimalField(decimal_places=2, default=1, max_digits=6, verbose_name='分值')),
                ('wrong_point_label', models.CharField(blank=True, max_length=128, verbose_name='错点标签')),
                ('image_path', models.CharField(blank=True, max_length=500, verbose_name='题目图片相对路径')),
                ('source_snapshot_json', models.JSONField(blank=True, default=dict, verbose_name='来源快照')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='entry.exampaper')),
            ],
            options={
                'verbose_name': '考试题目',
                'verbose_name_plural': '考试题目',
                'ordering': ['question_no', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_no', models.PositiveIntegerField(default=1, verbose_name='考试次数')),
                ('status', models.CharField(choices=[('assigned', '待开始'), ('in_progress', '考试中'), ('submitted', '已交卷'), ('auto_checked', '已判分'), ('expired', '已过期'), ('invalidated', '已作废')], default='assigned', max_length=16, verbose_name='考试状态')),
                ('total_count', models.PositiveIntegerField(default=0, verbose_name='总题数')),
                ('correct_count', models.PositiveIntegerField(default=0, verbose_name='正确数')),
                ('wrong_count', models.PositiveIntegerField(default=0, verbose_name='错误数')),
                ('total_score', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='总分')),
                ('earned_score', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='得分')),
                ('switch_count', models.PositiveIntegerField(default=0, verbose_name='切屏次数')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='提交时间')),
                ('checked_at', models.DateTimeField(blank=True, null=True, verbose_name='判分时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_exam_sessions', to='entry.portaluser')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='entry.exampaper')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_sessions', to='entry.student')),
            ],
            options={
                'verbose_name': '考试场次',
                'verbose_name_plural': '考试场次',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ExamProctorEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('visibility_hidden', '页面隐藏'), ('blur', '窗口失焦'), ('focus', '窗口聚焦'), ('screen_share_stopped', '停止共享屏幕'), ('paste', '粘贴')], max_length=32, verbose_name='事件类型')),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='发生时间')),
                ('metadata_json', models.JSONField(blank=True, default=dict, verbose_name='事件元数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proctor_events', to='entry.examsession')),
            ],
            options={
                'verbose_name': '考试监考事件',
                'verbose_name_plural': '考试监考事件',
                'ordering': ['occurred_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ExamSubmissionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_answer', models.CharField(blank=True, max_length=1, verbose_name='学生答案')),
                ('is_correct', models.BooleanField(default=False, verbose_name='是否正确')),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='得分')),
                ('correct_answer_snapshot', models.CharField(max_length=1, verbose_name='正确答案快照')),
                ('analysis_snapshot', models.TextField(blank=True, verbose_name='解析快照')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_answers', to='entry.examquestion')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='entry.examsession')),
            ],
            options={
                'verbose_name': '考试作答明细',
                'verbose_name_plural': '考试作答明细',
                'ordering': ['question_id', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='exampaper',
            index=models.Index(fields=['teacher', 'status', 'is_active'], name='exam_paper_teacher_status_idx'),
        ),
        migrations.AddIndex(
            model_name='exampaper',
            index=models.Index(fields=['course', 'status', 'is_active'], name='exam_paper_course_status_idx'),
        ),
        migrations.AddIndex(
            model_name='examquestion',
            index=models.Index(fields=['paper', 'is_active', 'question_no'], name='exam_question_paper_idx'),
        ),
        migrations.AddIndex(
            model_name='examquestion',
            index=models.Index(fields=['wrong_point_label', 'is_active'], name='exam_question_wrong_point_idx'),
        ),
        migrations.AddConstraint(
            model_name='examquestion',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('paper', 'question_no'), name='exam_q_paper_no_active_uniq'),
        ),
        migrations.AddIndex(
            model_name='examsession',
            index=models.Index(fields=['student', 'status', 'is_active'], name='exam_sess_student_status_idx'),
        ),
        migrations.AddIndex(
            model_name='examsession',
            index=models.Index(fields=['paper', 'status', 'is_active'], name='exam_sess_paper_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='examsession',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('paper', 'student', 'attempt_no'), name='exam_sess_student_attempt_uniq'),
        ),
        migrations.AddIndex(
            model_name='examproctorevent',
            index=models.Index(fields=['session', 'event_type', 'occurred_at'], name='exam_proc_session_event_idx'),
        ),
        migrations.AddIndex(
            model_name='examsubmissionanswer',
            index=models.Index(fields=['session', 'is_correct'], name='exam_ans_session_correct_idx'),
        ),
        migrations.AddConstraint(
            model_name='examsubmissionanswer',
            constraint=models.UniqueConstraint(fields=('session', 'question'), name='exam_answer_unique'),
        ),
    ]
