# Generated by Django 5.2.12 on 2026-06-02 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0034_exampaper_examquestion_examsession_examproctorevent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exampaper',
            name='mode',
            field=models.CharField(choices=[('timed', '定时考试'), ('deadline', 'DL考试')], default='deadline', max_length=16, verbose_name='考试模式'),
        ),
    ]
