# Generated by Django 5.2.12 on 2026-06-02 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0035_exampaper_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamQuestionBankItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_code', models.CharField(blank=True, max_length=32, verbose_name='等级')),
                ('knowledge_point', models.CharField(max_length=128, verbose_name='知识点')),
                ('source', models.CharField(choices=[('manual', '手动录入'), ('import', '文件导入'), ('scrape', '统一爬取')], default='manual', max_length=32, verbose_name='来源')),
                ('source_label', models.CharField(blank=True, max_length=255, verbose_name='来源说明')),
                ('source_url', models.CharField(blank=True, max_length=500, verbose_name='来源链接')),
                ('question_type', models.CharField(choices=[('single_choice', '单选题')], default='single_choice', max_length=32, verbose_name='题型')),
                ('stem', models.TextField(verbose_name='题面')),
                ('options_json', models.JSONField(blank=True, default=dict, verbose_name='选项')),
                ('correct_answer', models.CharField(max_length=1, verbose_name='答案')),
                ('analysis', models.TextField(blank=True, verbose_name='解析')),
                ('score', models.DecimalField(decimal_places=2, default=1, max_digits=6, verbose_name='默认分值')),
                ('image_path', models.CharField(blank=True, max_length=500, verbose_name='题目图片相对路径')),
                ('source_snapshot_json', models.JSONField(blank=True, default=dict, verbose_name='来源快照')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_question_bank_items', to='entry.coursecontent')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_question_bank_items', to='entry.course')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_exam_question_bank_items', to='entry.portaluser')),
            ],
            options={
                'verbose_name': '考试题库题目',
                'verbose_name_plural': '考试题库题目',
                'ordering': ['course_id', 'level_code', 'knowledge_point', 'id'],
                'indexes': [models.Index(fields=['course', 'is_active', 'level_code'], name='exam_bank_course_lvl_idx'), models.Index(fields=['knowledge_point', 'is_active'], name='exam_bank_kp_idx'), models.Index(fields=['source', 'is_active'], name='exam_bank_source_idx'), models.Index(fields=['created_by', 'is_active'], name='exam_bank_creator_idx')],
            },
        ),
    ]
