# Generated by Django 5.2.12 on 2026-06-03 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0036_examquestionbankitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamQuestionBankPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=32, verbose_name='级别')),
                ('year', models.PositiveSmallIntegerField(verbose_name='年份')),
                ('month', models.PositiveSmallIntegerField(verbose_name='月份')),
                ('source_pdf_id', models.CharField(max_length=128, verbose_name='来源 PDF ID')),
                ('source_file', models.CharField(blank=True, max_length=255, verbose_name='来源文件')),
                ('title', models.CharField(max_length=255, verbose_name='试卷标题')),
                ('import_batch_uid', models.CharField(blank=True, max_length=128, verbose_name='导入批次 UID')),
                ('source', models.CharField(choices=[('hermes', 'Hermes 题库')], default='hermes', max_length=32, verbose_name='来源')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '考试题库试卷快照',
                'verbose_name_plural': '考试题库试卷快照',
                'ordering': ['-year', '-month', 'level', 'source_pdf_id'],
                'indexes': [models.Index(fields=['level', 'year', 'month', 'is_active'], name='exam_bank_paper_lookup_idx'), models.Index(fields=['source', 'source_pdf_id'], name='exam_bank_paper_src_idx')],
                'constraints': [models.UniqueConstraint(fields=('source', 'source_pdf_id'), name='exam_bank_paper_src_uniq'), models.CheckConstraint(condition=models.Q(('month__gte', 1), ('month__lte', 12)), name='exam_bank_paper_month_ck')],
            },
        ),
        migrations.CreateModel(
            name='ExamQuestionBankQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_uid', models.CharField(db_index=True, max_length=128, verbose_name='外部题目 UID')),
                ('question_no', models.PositiveIntegerField(verbose_name='题号')),
                ('question_type', models.CharField(choices=[('single_choice', '单选题'), ('true_false', '判断题'), ('programming', '编程题')], max_length=32, verbose_name='题型')),
                ('stem_md', models.TextField(verbose_name='题干 Markdown')),
                ('answer_json', models.JSONField(blank=True, default=dict, verbose_name='标准答案')),
                ('analysis_md', models.TextField(blank=True, verbose_name='解析 Markdown')),
                ('programming_json', models.JSONField(blank=True, default=dict, verbose_name='编程题结构')),
                ('full_json', models.JSONField(blank=True, default=dict, verbose_name='Hermes 原始结构')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='entry.examquestionbankpaper')),
            ],
            options={
                'verbose_name': '考试题库题目快照',
                'verbose_name_plural': '考试题库题目快照',
                'ordering': ['paper_id', 'question_no', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ExamQuestionBankOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_key', models.CharField(max_length=16, verbose_name='选项')),
                ('option_text_md', models.TextField(blank=True, verbose_name='选项 Markdown')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='entry.examquestionbankquestion')),
            ],
            options={
                'verbose_name': '考试题库选项快照',
                'verbose_name_plural': '考试题库选项快照',
                'ordering': ['question_id', 'sort_order', 'option_key'],
            },
        ),
        migrations.CreateModel(
            name='ExamQuestionBankAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_uid', models.CharField(blank=True, default='', max_length=128, verbose_name='外部资源 UID')),
                ('asset_role', models.CharField(max_length=32, verbose_name='资源角色')),
                ('asset_type', models.CharField(blank=True, max_length=32, verbose_name='资源类型')),
                ('relative_path', models.CharField(blank=True, max_length=500, verbose_name='相对路径')),
                ('public_url', models.CharField(blank=True, max_length=500, verbose_name='公开 URL')),
                ('alt', models.CharField(blank=True, max_length=255, verbose_name='替代文本')),
                ('width', models.PositiveIntegerField(blank=True, null=True, verbose_name='宽度')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='高度')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='entry.examquestionbankquestion')),
            ],
            options={
                'verbose_name': '考试题库图片资源快照',
                'verbose_name_plural': '考试题库图片资源快照',
                'ordering': ['question_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PublishedExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='考试标题')),
                ('level', models.CharField(max_length=32, verbose_name='级别')),
                ('mode', models.CharField(choices=[('timed', '定时考试'), ('deadline', 'DL考试')], default='deadline', max_length=16, verbose_name='考试模式')),
                ('duration_minutes', models.PositiveIntegerField(default=60, verbose_name='考试时长（分钟）')),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='结束/截止时间')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('scheduled', '已定时'), ('active', '进行中'), ('closed', '已结束'), ('archived', '已归档')], default='draft', max_length=16, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_published_exams', to='entry.portaluser')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='published_exams', to='entry.examquestionbankpaper')),
            ],
            options={
                'verbose_name': '发布考试',
                'verbose_name_plural': '发布考试',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PublishedExamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', '未开始'), ('in_progress', '考试中'), ('submitted', '已提交'), ('graded', '已判分')], default='not_started', max_length=16, verbose_name='状态')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='提交时间')),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='得分')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('published_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='entry.publishedexam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='published_exam_sessions', to='entry.student')),
            ],
            options={
                'verbose_name': '发布考试学生场次',
                'verbose_name_plural': '发布考试学生场次',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PublishedExamAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_json', models.JSONField(blank=True, default=dict, verbose_name='学生答案')),
                ('is_correct', models.BooleanField(default=False, verbose_name='是否正确')),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='得分')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='published_answers', to='entry.examquestionbankquestion')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='entry.publishedexamsession')),
            ],
            options={
                'verbose_name': '发布考试作答',
                'verbose_name_plural': '发布考试作答',
                'ordering': ['question_id', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='examquestionbankquestion',
            index=models.Index(fields=['paper', 'question_no'], name='exam_bank_q_paper_no_idx'),
        ),
        migrations.AddIndex(
            model_name='examquestionbankquestion',
            index=models.Index(fields=['question_type'], name='exam_bank_q_type_idx'),
        ),
        migrations.AddConstraint(
            model_name='examquestionbankquestion',
            constraint=models.UniqueConstraint(fields=('paper', 'question_uid'), name='exam_bank_q_uid_uniq'),
        ),
        migrations.AddConstraint(
            model_name='examquestionbankquestion',
            constraint=models.UniqueConstraint(fields=('paper', 'question_no'), name='exam_bank_q_no_uniq'),
        ),
        migrations.AddIndex(
            model_name='examquestionbankoption',
            index=models.Index(fields=['question', 'sort_order'], name='exam_bank_opt_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='examquestionbankoption',
            constraint=models.UniqueConstraint(fields=('question', 'option_key'), name='exam_bank_opt_key_uniq'),
        ),
        migrations.AddIndex(
            model_name='examquestionbankasset',
            index=models.Index(fields=['question', 'asset_role'], name='exam_bank_asset_role_idx'),
        ),
        migrations.AddConstraint(
            model_name='examquestionbankasset',
            constraint=models.UniqueConstraint(condition=models.Q(('asset_uid', ''), _negated=True), fields=('question', 'asset_uid'), name='exam_bank_asset_uid_uniq'),
        ),
        migrations.AddConstraint(
            model_name='examquestionbankasset',
            constraint=models.UniqueConstraint(condition=models.Q(('relative_path', ''), _negated=True), fields=('question', 'asset_role', 'relative_path'), name='exam_bank_asset_path_uniq'),
        ),
        migrations.AddIndex(
            model_name='publishedexam',
            index=models.Index(fields=['level', 'status'], name='pub_exam_level_status_idx'),
        ),
        migrations.AddIndex(
            model_name='publishedexam',
            index=models.Index(fields=['status', 'starts_at'], name='pub_exam_status_start_idx'),
        ),
        migrations.AddIndex(
            model_name='publishedexam',
            index=models.Index(fields=['paper', 'status'], name='pub_exam_paper_status_idx'),
        ),
        migrations.AddIndex(
            model_name='publishedexamsession',
            index=models.Index(fields=['student', 'status'], name='pub_exam_sess_student_idx'),
        ),
        migrations.AddIndex(
            model_name='publishedexamsession',
            index=models.Index(fields=['published_exam', 'status'], name='pub_exam_sess_exam_idx'),
        ),
        migrations.AddConstraint(
            model_name='publishedexamsession',
            constraint=models.UniqueConstraint(fields=('published_exam', 'student'), name='pub_exam_sess_unique'),
        ),
        migrations.AddIndex(
            model_name='publishedexamanswer',
            index=models.Index(fields=['session', 'is_correct'], name='pub_exam_ans_correct_idx'),
        ),
        migrations.AddConstraint(
            model_name='publishedexamanswer',
            constraint=models.UniqueConstraint(fields=('session', 'question'), name='pub_exam_answer_unique'),
        ),
    ]
