# Generated by Django 5.2.12 on 2026-06-09 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0037_examquestionbankpaper_examquestionbankquestion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exampaper',
            name='access_code',
            field=models.CharField(blank=True, max_length=6, verbose_name='考试入口口令'),
        ),
        migrations.AddField(
            model_name='exampaper',
            name='access_code_generated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='口令生成时间'),
        ),
        migrations.AddIndex(
            model_name='exampaper',
            index=models.Index(fields=['access_code', 'is_active'], name='exam_paper_access_code_idx'),
        ),
    ]
