# Generated by Django 5.2.12 on 2026-06-10 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0038_exam_access_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamQuestionBankImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_code', models.CharField(max_length=32, verbose_name='级别/类别')),
                ('title', models.CharField(max_length=255, verbose_name='试卷标题')),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='年份')),
                ('month', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='月份')),
                ('source_pdf_id', models.CharField(max_length=128, verbose_name='来源 PDF ID')),
                ('source_pdf', models.FileField(upload_to='exam_paper_imports/%Y/%m/%d', verbose_name='源 PDF')),
                ('source_filename', models.CharField(max_length=255, verbose_name='原始文件名')),
                ('source_sha256', models.CharField(blank=True, default='', max_length=64, verbose_name='源文件内容哈希')),
                ('status', models.CharField(choices=[('uploaded', '已上传'), ('rendering', '页面截图中'), ('ocr_running', 'Qwen OCR 中'), ('ocr_done', 'OCR 已完成'), ('failed', '识别失败'), ('imported', '已入题库'), ('cancelled', '已取消')], default='uploaded', max_length=32, verbose_name='状态')),
                ('status_notes', models.TextField(blank=True, verbose_name='状态备注')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('workspace_relative_path', models.CharField(blank=True, max_length=500, verbose_name='中间产物相对路径')),
                ('rendered_pages_json', models.JSONField(blank=True, default=list, verbose_name='页面截图')),
                ('raw_ocr_json', models.JSONField(blank=True, default=list, verbose_name='逐页 OCR 结果')),
                ('qwen_model', models.CharField(blank=True, max_length=128, verbose_name='Qwen OCR 模型')),
                ('qwen_base_url', models.CharField(blank=True, max_length=500, verbose_name='Qwen Base URL')),
                ('page_count', models.PositiveIntegerField(default=0, verbose_name='PDF 页数')),
                ('rendered_page_count', models.PositiveIntegerField(default=0, verbose_name='已截图页数')),
                ('ocr_page_count', models.PositiveIntegerField(default=0, verbose_name='已 OCR 页数')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_question_bank_import_jobs', to='entry.course')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_question_bank_import_jobs', to='entry.portaluser')),
            ],
            options={
                'verbose_name': '考试题库 PDF 导入任务',
                'verbose_name_plural': '考试题库 PDF 导入任务',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['teacher', 'status', 'is_active'], name='exam_qb_imp_teacher_idx'), models.Index(fields=['course', 'level_code', 'status'], name='exam_qb_imp_course_idx'), models.Index(fields=['source_pdf_id', 'status'], name='exam_qb_imp_pdf_idx'), models.Index(fields=['source_sha256', 'created_at'], name='exam_qb_imp_sha_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('month__isnull', True), models.Q(('month__gte', 1), ('month__lte', 12)), _connector='OR'), name='exam_qb_imp_month_ck')],
            },
        ),
    ]
