# Generated by Codex on 2026-06-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entry", "0040_exam_question_bank_local_ocr_choices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="examquestion",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("single_choice", "单选题"),
                    ("true_false", "判断题"),
                    ("programming", "编程题"),
                ],
                default="single_choice",
                max_length=32,
                verbose_name="题型",
            ),
        ),
    ]
