# Generated by Django 5.2.12 on 2026-06-11 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0041_alter_examquestion_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsession',
            name='question_scope_json',
            field=models.JSONField(blank=True, default=dict, verbose_name='练习题目范围'),
        ),
        migrations.AddField(
            model_name='examsession',
            name='session_type',
            field=models.CharField(choices=[('exam', '正式考试'), ('full_practice', '整卷练习'), ('wrong_practice', '错题练习')], default='exam', max_length=32, verbose_name='场次类型'),
        ),
        migrations.AddField(
            model_name='examsubmissionanswer',
            name='explanation_text',
            field=models.TextField(blank=True, verbose_name='学生解析'),
        ),
    ]
