# Generated by Django 5.2.12 on 2026-06-11 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0042_examsession_question_scope_json_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examquestion',
            name='important_marked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='重点标记时间'),
        ),
        migrations.AddField(
            model_name='examquestion',
            name='important_marked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='important_exam_questions', to='entry.portaluser'),
        ),
        migrations.AddField(
            model_name='examquestion',
            name='important_note',
            field=models.TextField(blank=True, verbose_name='重点说明'),
        ),
        migrations.AddField(
            model_name='examquestion',
            name='is_important',
            field=models.BooleanField(default=False, verbose_name='是否标记重点'),
        ),
    ]
