# Generated by Django 5.2.12 on 2026-06-15 10:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0043_examquestion_important_marked_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_code', models.CharField(max_length=6, verbose_name='考试入口口令')),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='口令生成时间')),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='场次开始时间')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='场次结束时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_exam_runs', to='entry.portaluser')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='entry.exampaper')),
            ],
            options={
                'verbose_name': '考试场次',
                'verbose_name_plural': '考试场次',
                'ordering': ['-generated_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='examsession',
            name='exam_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='entry.examrun'),
        ),
        migrations.AddIndex(
            model_name='examsession',
            index=models.Index(fields=['exam_run', 'status', 'is_active'], name='exam_sess_run_status_idx'),
        ),
        migrations.AddIndex(
            model_name='examrun',
            index=models.Index(fields=['paper', 'is_active', 'generated_at'], name='exam_run_paper_time_idx'),
        ),
        migrations.AddIndex(
            model_name='examrun',
            index=models.Index(fields=['access_code', 'is_active'], name='exam_run_code_idx'),
        ),
    ]
