# Generated by Codex on 2026-06-15

from django.db import migrations


def backfill_exam_runs(apps, schema_editor):
    ExamPaper = apps.get_model("entry", "ExamPaper")
    ExamRun = apps.get_model("entry", "ExamRun")
    ExamSession = apps.get_model("entry", "ExamSession")

    papers = ExamPaper.objects.filter(is_active=True).exclude(access_code="")
    for paper in papers.iterator():
        generated_at = paper.access_code_generated_at or paper.created_at
        run, _ = ExamRun.objects.get_or_create(
            paper_id=paper.id,
            access_code=paper.access_code,
            defaults={
                "generated_at": generated_at,
                "starts_at": paper.start_at,
                "ends_at": paper.end_at,
                "created_by_id": paper.teacher_id,
                "is_active": True,
            },
        )
        ExamSession.objects.filter(
            paper_id=paper.id,
            exam_run__isnull=True,
            session_type="exam",
        ).update(exam_run_id=run.id)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("entry", "0044_examrun_examsession_exam_run_and_more"),
    ]

    operations = [
        migrations.RunPython(backfill_exam_runs, noop_reverse),
    ]
