# Generated by Codex on 2026-06-15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entry", "0045_backfill_exam_runs"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamQuestionAnalysisBlock",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("ai", "AI 解析"),
                            ("teacher", "老师解析"),
                            ("student", "学生贡献"),
                            ("merged", "汇总解析"),
                        ],
                        default="teacher",
                        max_length=32,
                        verbose_name="解析来源",
                    ),
                ),
                ("content_md", models.TextField(verbose_name="解析 Markdown")),
                ("contributors_json", models.JSONField(blank=True, default=list, verbose_name="贡献者快照")),
                ("is_visible", models.BooleanField(default=True, verbose_name="是否展示")),
                ("sort_order", models.PositiveIntegerField(default=0, verbose_name="排序")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_exam_analysis_blocks",
                        to="entry.portaluser",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis_blocks",
                        to="entry.examquestion",
                    ),
                ),
            ],
            options={
                "verbose_name": "考试题目解析块",
                "verbose_name_plural": "考试题目解析块",
                "ordering": ["question_id", "sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ExamQuestionAnalysisSuggestion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("content_md", models.TextField(verbose_name="学生解析 Markdown")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待审核"),
                            ("accepted", "已采纳"),
                            ("rejected", "已忽略"),
                            ("merged", "已汇总"),
                        ],
                        default="pending",
                        max_length=32,
                        verbose_name="状态",
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True, verbose_name="审核时间")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "accepted_block",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_suggestions",
                        to="entry.examquestionanalysisblock",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis_suggestions",
                        to="entry.examquestion",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_exam_analysis_suggestions",
                        to="entry.portaluser",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="analysis_suggestions",
                        to="entry.examsession",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_analysis_suggestions",
                        to="entry.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "考试题目解析建议",
                "verbose_name_plural": "考试题目解析建议",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="examquestionanalysisblock",
            index=models.Index(fields=["question", "is_visible", "sort_order"], name="exam_analysis_q_visible_idx"),
        ),
        migrations.AddIndex(
            model_name="examquestionanalysisblock",
            index=models.Index(fields=["source_type", "is_visible"], name="exam_analysis_source_idx"),
        ),
        migrations.AddIndex(
            model_name="examquestionanalysissuggestion",
            index=models.Index(fields=["question", "status", "created_at"], name="exam_analysis_sug_q_idx"),
        ),
        migrations.AddIndex(
            model_name="examquestionanalysissuggestion",
            index=models.Index(fields=["student", "status", "created_at"], name="exam_analysis_sug_stu_idx"),
        ),
        migrations.AddIndex(
            model_name="examquestionanalysissuggestion",
            index=models.Index(fields=["session", "status"], name="exam_analysis_sug_sess_idx"),
        ),
    ]
