# Generated by Codex on 2026-06-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entry", "0046_exam_question_analysis"),
    ]

    operations = [
        migrations.AddField(
            model_name="examquestionbankpaper",
            name="analysis_generation_status",
            field=models.CharField(
                choices=[
                    ("not_started", "未生成"),
                    ("running", "解析中"),
                    ("completed", "解析完成"),
                    ("partial", "部分完成"),
                    ("failed", "解析失败"),
                ],
                default="not_started",
                max_length=32,
                verbose_name="AI 解析状态",
            ),
        ),
        migrations.AddField(
            model_name="examquestionbankpaper",
            name="analysis_generation_started_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="AI 解析开始时间"),
        ),
        migrations.AddField(
            model_name="examquestionbankpaper",
            name="analysis_generation_completed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="AI 解析完成时间"),
        ),
        migrations.AddField(
            model_name="examquestionbankpaper",
            name="analysis_generation_total_count",
            field=models.PositiveIntegerField(default=0, verbose_name="AI 解析总题数"),
        ),
        migrations.AddField(
            model_name="examquestionbankpaper",
            name="analysis_generation_done_count",
            field=models.PositiveIntegerField(default=0, verbose_name="AI 解析完成题数"),
        ),
        migrations.AddField(
            model_name="examquestionbankpaper",
            name="analysis_generation_failed_count",
            field=models.PositiveIntegerField(default=0, verbose_name="AI 解析失败题数"),
        ),
        migrations.AddField(
            model_name="examquestionbankpaper",
            name="analysis_generation_error",
            field=models.TextField(blank=True, verbose_name="AI 解析错误"),
        ),
    ]
