# Generated by Codex on 2026-06-16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("entry", "0047_exam_bank_paper_analysis_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentSiteMessage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=160, verbose_name="标题")),
                ("body", models.TextField(blank=True, verbose_name="正文")),
                ("target_href", models.CharField(blank=True, max_length=500, verbose_name="跳转链接")),
                ("is_read", models.BooleanField(default=False, verbose_name="是否已读")),
                ("read_at", models.DateTimeField(blank=True, null=True, verbose_name="阅读时间")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "source_suggestion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="student_site_messages",
                        to="entry.examquestionanalysissuggestion",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="site_messages",
                        to="entry.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "学生站内信",
                "verbose_name_plural": "学生站内信",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="studentsitemessage",
            index=models.Index(fields=["student", "is_read", "created_at"], name="student_msg_unread_idx"),
        ),
        migrations.AddIndex(
            model_name="studentsitemessage",
            index=models.Index(fields=["source_suggestion"], name="student_msg_suggestion_idx"),
        ),
    ]
