# Generated by Codex on 2026-06-17

from pathlib import Path

from django.conf import settings
from django.db import migrations, models


def parse_markdown_table_rows(markdown_text):
    rows = []
    in_table = False
    for raw_line in markdown_text.splitlines():
        line = raw_line.strip()
        if not line.startswith("|") or not line.endswith("|"):
            if in_table:
                break
            continue
        cells = [cell.strip() for cell in line.strip("|").split("|")]
        if len(cells) < 3:
            continue
        if cells[0] == "一级目录" or set(cells[0]) <= {"-"}:
            in_table = True
            continue
        in_table = True
        level_1, level_2, level_3 = cells[:3]
        if level_1 and level_2:
            rows.append((level_1, level_2, level_3))
    return rows


def seed_gesp2_cpp_knowledge_map(apps, schema_editor):
    ExamKnowledgePointMap = apps.get_model("entry", "ExamKnowledgePointMap")
    mapping_path = Path(settings.BASE_DIR) / "knowledge_mappings" / "cpp" / "GESP2知识对照.md"
    if not mapping_path.is_file():
        return
    rows = parse_markdown_table_rows(mapping_path.read_text(encoding="utf-8"))
    for index, (level_1, level_2, level_3) in enumerate(rows, start=1):
        ExamKnowledgePointMap.objects.update_or_create(
            subject="cpp",
            category_code="GESP2",
            level_1=level_1,
            level_2=level_2,
            level_3=level_3,
            defaults={
                "source_path": "knowledge_mappings/cpp/GESP2知识对照.md",
                "sort_order": index,
                "is_active": True,
            },
        )


def unseed_gesp2_cpp_knowledge_map(apps, schema_editor):
    ExamKnowledgePointMap = apps.get_model("entry", "ExamKnowledgePointMap")
    ExamKnowledgePointMap.objects.filter(subject="cpp", category_code="GESP2").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("entry", "0048_student_site_message"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamKnowledgePointMap",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("subject", models.CharField(max_length=32, verbose_name="所属学科")),
                ("category_code", models.CharField(max_length=32, verbose_name="所属类别")),
                ("level_1", models.CharField(max_length=128, verbose_name="一级目录")),
                ("level_2", models.CharField(max_length=128, verbose_name="二级目录")),
                ("level_3", models.CharField(blank=True, max_length=255, verbose_name="三级目录")),
                ("source_path", models.CharField(blank=True, max_length=255, verbose_name="来源文件")),
                ("sort_order", models.PositiveIntegerField(default=0, verbose_name="排序")),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
            ],
            options={
                "verbose_name": "考试知识点映射",
                "verbose_name_plural": "考试知识点映射",
                "ordering": ["subject", "category_code", "sort_order", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="examknowledgepointmap",
            constraint=models.UniqueConstraint(
                fields=("subject", "category_code", "level_1", "level_2", "level_3"),
                name="exam_kp_map_unique_path",
            ),
        ),
        migrations.AddIndex(
            model_name="examknowledgepointmap",
            index=models.Index(fields=["subject", "category_code", "is_active"], name="exam_kp_map_scope_idx"),
        ),
        migrations.AddIndex(
            model_name="examknowledgepointmap",
            index=models.Index(fields=["level_1", "level_2"], name="exam_kp_map_l1_l2_idx"),
        ),
        migrations.AddIndex(
            model_name="examknowledgepointmap",
            index=models.Index(fields=["level_3"], name="exam_kp_map_l3_idx"),
        ),
        migrations.RunPython(seed_gesp2_cpp_knowledge_map, unseed_gesp2_cpp_knowledge_map),
    ]
