# Generated by Codex on 2026-06-19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("entry", "0053_teacher_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="examknowledgepointmap",
            name="course_level_code",
            field=models.CharField(blank=True, max_length=16, verbose_name="课程级别"),
        ),
        migrations.AddField(
            model_name="examknowledgepointmap",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="uploaded_exam_knowledge_maps",
                to="entry.portaluser",
                verbose_name="操作人",
            ),
        ),
    ]
