# Generated by Codex on 2026-06-24

import uuid

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("entry", "0054_exam_knowledge_point_map_upload_metadata"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgrammingSubmission",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "platform",
                    models.CharField(
                        choices=[("scratch", "Scratch"), ("cpp", "C++")],
                        default="scratch",
                        max_length=32,
                        verbose_name="平台",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "草稿"), ("submitted", "已提交"), ("reviewed", "已查阅")],
                        default="draft",
                        max_length=32,
                        verbose_name="状态",
                    ),
                ),
                ("launch_token", models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name="启动令牌")),
                ("editor_url", models.CharField(blank=True, max_length=500, verbose_name="编辑器地址")),
                ("project_title", models.CharField(blank=True, max_length=255, verbose_name="作品标题")),
                ("project_file_path", models.CharField(blank=True, max_length=500, verbose_name="作品文件路径")),
                ("project_url", models.CharField(blank=True, max_length=500, verbose_name="作品访问地址")),
                ("screenshot_path", models.CharField(blank=True, max_length=500, verbose_name="作品截图路径")),
                ("artifacts_json", models.JSONField(blank=True, default=dict, verbose_name="作品附件信息")),
                ("learning_events_json", models.JSONField(blank=True, default=dict, verbose_name="学习事件摘要")),
                ("ai_summary_json", models.JSONField(blank=True, default=dict, verbose_name="AI 助手摘要")),
                ("last_saved_at", models.DateTimeField(blank=True, null=True, verbose_name="最近保存时间")),
                ("submitted_at", models.DateTimeField(blank=True, null=True, verbose_name="提交时间")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "exam_question",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="programming_submissions",
                        to="entry.examquestion",
                    ),
                ),
                (
                    "exam_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="programming_submissions",
                        to="entry.examsession",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="programming_submissions",
                        to="entry.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "编程提交",
                "verbose_name_plural": "编程提交",
                "ordering": ["-updated_at", "-id"],
                "indexes": [
                    models.Index(fields=["student", "platform", "status"], name="prog_sub_student_status_idx"),
                    models.Index(fields=["exam_session", "exam_question"], name="prog_sub_exam_question_idx"),
                    models.Index(fields=["launch_token"], name="prog_sub_launch_token_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("student", "exam_session", "exam_question", "platform"),
                        name="programming_submission_exam_unique",
                    ),
                ],
            },
        ),
    ]
